### PR TITLE
Some minor bug fixes

### PR DESCRIPTION
**Pull request by blondie7575**
- New Video register was missing Linearize Video Memory bit
- Memory copy loops were starting one byte past the end and skipping the 0th byte

### CODE REVIEW

**Comment by digarok** [comment]
Thanks for looking into this.  

Regarding the loops, by moving the address down by two, including the pre-decrement of X, I believe you've now written it in a way that is now shifted below the desired addresses.

Imagine we enter this function:
```

ClearToColor  ldx   #$7D00      ;X=$7D00
:clearloop    dex               ;X=$7CFF
              dex               ;X=$7CFE
              stal  $E11FFE,x   ;$E11FFE+$7CFE = $E19CFC  (We wanted the word at $E19CFE.FF)
```

Or at the last iteration of the function when we hit zero (remember STA does not affect flags):
```
:clearloop    dex               ;X=$0001
              dex               ;X=$0000
              stal  $E11FFE,x   ;$E11FFE+$0000 = $E11FFE  (We wanted the word at $E12000.2001)
```

I've just checked the original loops in a debugger and they seem correct to me, but maybe I'm missing something?

**Comment by blondie7575** [comment]
Oops, you're correct. In my head the stores were before the dexes, because that's how I always write a loop like that. 😝

**Comment by digarok** [comment]
Do you think that since this is meant to be more of a tutorial for beginners that this is too confusing? Maybe it's better to use the idiom of starting at zero and incrementing and taking the performance hit of a comparison / iteration. What do you think?

**Comment by blondie7575** [comment]
Nah, I think it’s fine as-is. It was certainly helpful for me to see how you’re setting up the SCBs and Palettes. The one odd thing is the $81 being set to $c029, which contradicts your videos (and seemingly the Apple documentation, although the code as you have it here does work).

**Pull request closed without merging**
